package com.music.music_inventory_api.repository;

import com.music.music_inventory_api.entity.OrderItem;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.util.List;

/**
 * Repository interface for OrderItem entity.
 * Provides CRUD operations and custom queries for order item data access.
 */
@Repository
public interface OrderItemRepository extends JpaRepository<OrderItem, Long> 
{
    List<OrderItem> findByOrderId(Long orderId);

    List<OrderItem> findByAlbumId(Long albumId);

    /**
     * Custom query to calculate total quantity sold for an album.
     *
     * @param albumId the album ID
     * @return total quantity sold
     */
    @Query("SELECT COALESCE(SUM(oi.quantity), 0) FROM OrderItem oi " +
           "WHERE oi.album.id = :albumId")
    Long calculateTotalQuantitySold(@Param("albumId") Long albumId);

    /**
     * Custom query to calculate total revenue for an album.
     *
     * @param albumId the album ID
     * @return total revenue generated by the album
     */
    @Query("SELECT COALESCE(SUM(oi.unitPrice * oi.quantity), 0) FROM OrderItem oi " +
           "WHERE oi.album.id = :albumId")
    BigDecimal calculateAlbumRevenue(@Param("albumId") Long albumId);

    /**
     * Custom query to find order items by customer ID (through order).
     *
     * @param customerId the customer ID
     * @return list of order items purchased by the customer
     */
    @Query("SELECT oi FROM OrderItem oi " +
           "JOIN oi.order o " +
           "WHERE o.customer.id = :customerId " +
           "ORDER BY o.createdAt DESC")
    List<OrderItem> findByCustomerId(@Param("customerId") Long customerId);

    /**
     * Custom query to find most popular albums (by quantity sold).
     *
     * @param limit maximum number of results
     * @return list of order items grouped by album, ordered by total quantity
     */
    @Query("SELECT oi.album.id, SUM(oi.quantity) as totalQty " +
           "FROM OrderItem oi " +
           "GROUP BY oi.album.id " +
           "ORDER BY totalQty DESC")
    List<Object[]> findMostPopularAlbums(@Param("limit") int limit);
}

